version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          name: Restore Cached Dependencies
          keys:
            - hledger-flow-v1-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
      - run:
          name: Link statically on Linux
          command: sed -i 's/- -dynamic /- -static  /g' package.yaml
      - run:
          name: Resolve/Update Dependencies
          command: stack setup --interleaved-output
      - run:
          name: Stack Build
          command: stack build --interleaved-output --test --bench --no-run-tests --no-run-benchmarks --ghc-options=-Werror
      - run:
          name: Run tests
          command: stack test --interleaved-output
      - run:
          name: Install hledger-flow executable
          command: stack install
      - run:
          name: hledger-flow --version
          command: ~/.local/bin/hledger-flow --version
      - run:
          name: List hledger-flow shared object dependencies - should not be dynamic
          command: ldd ~/.local/bin/hledger-flow || true
      - run:
          name: Build Release Tarball
          command: ./bin/release-tarball ~/.local/bin/hledger-flow
      - run:
          name: Install hledger
          command: stack install hledger
      - run:
          name: Show hledger version
          command: hledger --version
      - run:
          name: Clone hledger-flow-example
          command: git clone --recurse-submodules https://github.com/apauley/hledger-flow-example.git $HOME/hledger-flow-example
      - run:
          name: hledger-flow import
          command: ~/.local/bin/hledger-flow import --show-options --verbose $HOME/hledger-flow-example
      - run:
          name: hledger-flow report
          command: ~/.local/bin/hledger-flow report --show-options --verbose $HOME/hledger-flow-example
      - run:
          name: Undo package.yaml change before cache_save
          command: git checkout HEAD package.yaml
      - save_cache:
          name: Cache Dependencies
          key: hledger-flow-v1-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - store_artifacts:
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: ./releases
